"use client";

import { Fragment, useEffect, useMemo, useRef, useState } from "react";
import { PriceChart } from "@/components/fog/PriceChart";
import GexHeatmap from "@/components/fog/GexHeatmap";
import type { HeatmapFrame } from "@/components/fog/GexHeatmap";

/**
 * Fog — 0DTE GEX/DEX terminal landing surface.
 *
 * Data source: fetches real snapshot JSON from /data/ES_<date>.json
 * (generated by gen_session_snapshots.py). Falls back to synthetic data
 * if fetch fails (dev convenience).
 *
 * Layout principles (per design spec, 2026-06-16 rev2):
 *   - Minimalism: no heavy borders. Hairline rules separate the three zones
 *     (price ladder | GEX profile | chart). Bar pills are rounded, not boxy.
 *   - Selector dropdown (top-left): GEX / VEX / CEX / DEX. Click opens, click
 *     item selects, click-outside closes. Hover text → red.
 *   - GEX profile (left rail):
 *       · Each row = one strike. Background hairline = full historical
 *         GEX range (low ↔ high). Foreground pill = current GEX value.
 *       · Pills are rounded-full (lozenge), bidirectional from a center axis.
 *       · Center vertical line = zero-axis.
 *       · Rows are tightly packed but visibly separated.
 *       · Color: deep turquoise = long GEX, deep crimson = short GEX.
 *   - Price ladder (leftmost): font-color only (no fill).
 *       · Amber  = current price
 *       · Turquoise = level with major net long GEX
 *       · Crimson   = level with major net short GEX
 *   - Center: chart placeholder.
 *   - Right rail: turquoise→black→crimson heatmap gradient.
 *   - Bottom-left: flash glyph.
 */

const SELECTORS = ["GEX", "DEX"] as const;
type Selector = (typeof SELECTORS)[number];

// Snapshot JSON types (matches engine output)
interface SnapshotProfile {
  strike: number;
  net_gex: number;
  net_dex: number;
  interpolated: boolean;
}

interface SnapshotLevels {
  gamma_flip: number;
  call_walls: number[];
  put_walls: number[];
  largest_gex: number;
  largest_dex: number;
}

interface SnapshotRegime {
  net_gamma: number;
  sign: number;
  stability_pct: number;
}

interface SnapshotFlux {
  total: number;
  calls: number;
  puts: number;
  zerodte: number;
  retail: number;
}

interface SnapshotFog {
  price_grid: number[];
  gamma: number[];
  delta: number[];
}

interface Snapshot {
  forward: number;
  minute_index: number;
  ts: string;
  profile: SnapshotProfile[];
  levels: SnapshotLevels;
  regime: SnapshotRegime;
  flux: SnapshotFlux | null;
  fog: SnapshotFog;
}

// Strike data for display (normalized from snapshot)
interface StrikeData {
  price: number;
  current: number; // normalized to [-1, 1]
  low: number;
  high: number;
  absCurrent: number; // raw value
  absLow: number;
  absHigh: number;
  diff5m: number;
  diff30m: number;
  diff60m: number;
}

// One point of the forward-price line (UTC epoch seconds + price).
interface ForwardPoint {
  time: number;
  value: number;
}

// Fallback synthetic data if snapshot fetch fails
function genSyntheticStrikes(): StrikeData[] {
  const STRIKE_COUNT = 24;
  const BASE_PRICE = 5_840;
  const TICK = 5;
  return Array.from({ length: STRIKE_COUNT }, (_, i) => {
    const price = BASE_PRICE + (STRIKE_COUNT - 1 - i) * TICK;
    const seed = (n: number) => {
      const t = Math.sin(i * 91.345 + n * 17.13) * 43758.5453;
      return t - Math.floor(t);
    };
    const current = (seed(1) - 0.5) * 2 * (0.4 + seed(2) * 0.6);
    const range = 0.25 + seed(3) * 0.55;
    const low = Math.max(-1, current - range * (0.3 + seed(4) * 0.7));
    const high = Math.min(1, current + range * (0.3 + seed(5) * 0.7));
    return {
      price,
      current,
      low,
      high,
      absCurrent: current * 1e9,
      absLow: low * 1e9,
      absHigh: high * 1e9,
      diff5m: 100e6,
      diff30m: -200e6,
      diff60m: 150e6,
    };
  });
}

// Map selector to the per-strike field name in SnapshotProfile
function getFieldForSelector(sel: Selector): "net_gex" | "net_dex" {
  return sel === "DEX" ? "net_dex" : "net_gex";
}

export default function FogPage() {
  const [selector, setSelector] = useState<Selector>("GEX");
  const [open, setOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement | null>(null);

  // Snapshot data state
  // All frames of the session — needed to compute per-strike historical
  // high/low (the grey range hairline) and the latest stats.
  const [frames, setFrames] = useState<Snapshot[]>([]);
  const [forward, setForward] = useState<number>(5872);
  const [regime, setRegime] = useState<string>("Neutral");
  const [pcRatio, setPcRatio] = useState<string>("1.00");
  // Forward-price line series for the chart (one point per RTH minute).
  const [forwardSeries, setForwardSeries] = useState<ForwardPoint[]>([]);

  // Fetch snapshot JSON on mount
  useEffect(() => {
    const date = "2026-06-09";
    const instrument = "ES";
    const url = `/data/${instrument}_${date}.json`;

    fetch(url)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data: Snapshot[]) => {
        if (!data || data.length === 0) {
          throw new Error("Empty snapshot array");
        }

        setFrames(data);

        // Build the forward-price line: one point per frame (UTC epoch seconds).
        const series: ForwardPoint[] = data.map((f) => ({
          time: Math.floor(new Date(f.ts).getTime() / 1000),
          value: f.forward,
        }));
        setForwardSeries(series);

        // Latest frame = the actual current state of the session (last minute).
        const frame = data[data.length - 1];

        setForward(frame.forward);

        // Derive gamma regime from net_gamma
        const netGamma = frame.regime.net_gamma;
        const regimeStr =
          netGamma > 0 ? "Long Gamma" : netGamma < 0 ? "Short Gamma" : "Neutral";
        setRegime(regimeStr);

        // P/C ratio from flux (puts vs calls dealer delta-notional). Falls back
        // to 1.00 when flux is absent (contract-valid optional field).
        if (frame.flux && frame.flux.calls !== 0) {
          const ratio = Math.abs(frame.flux.puts / frame.flux.calls);
          setPcRatio(ratio.toFixed(2));
        } else {
          setPcRatio("1.00");
        }
      })
      .catch((err) => {
        console.warn("Snapshot fetch failed, using synthetic fallback:", err);
        setFrames([]);
        setForward(5872);
        setRegime("Neutral");
        setPcRatio("1.00");
      });
  }, []);

  // Derive strikes from frames + selector (reactive).
  //   · current = latest frame's value for this strike
  //   · low/high = real historical min/max across the WHOLE session
  // All normalized by the session-wide max |value| so bars + range hairline
  // share one scale. The grey hairline therefore marks where each strike has
  // actually been (its lowest ↔ highest reading during the day).
  const strikes = useMemo<StrikeData[]>(() => {
    if (frames.length === 0) {
      return genSyntheticStrikes();
    }
    const field = getFieldForSelector(selector);

    // Accumulate per-strike: latest value + running min/max across frames.
    const byStrike = new Map<
      number,
      { latest: number; low: number; high: number; history: number[] }
    >();
    for (const f of frames) {
      for (const p of f.profile) {
        if (p.interpolated) continue;
        const v = p[field] as number;
        const entry = byStrike.get(p.strike);
        if (entry) {
          entry.latest = v; // frames are chronological → last write is latest
          entry.low = Math.min(entry.low, v);
          entry.high = Math.max(entry.high, v);
          entry.history.push(v);
        } else {
          byStrike.set(p.strike, { latest: v, low: v, high: v, history: [v] });
        }
      }
    }

    // Session-wide scale: largest absolute value seen anywhere (current or hist).
    let maxAbs = 1;
    for (const e of byStrike.values()) {
      maxAbs = Math.max(maxAbs, Math.abs(e.latest), Math.abs(e.low), Math.abs(e.high));
    }

    const normalized: StrikeData[] = Array.from(byStrike.entries()).map(
      ([price, e]) => {
        const histLen = e.history.length;
        const idx60 = Math.max(0, histLen - 60);
        const idx30 = Math.max(0, histLen - 30);
        const idx5 = Math.max(0, histLen - 5);
        return {
          price,
          current: e.latest / maxAbs,
          low: e.low / maxAbs,
          high: e.high / maxAbs,
          absCurrent: e.latest,
          absLow: e.low,
          absHigh: e.high,
          diff5m: e.latest - (e.history[idx5] ?? e.latest),
          diff30m: e.latest - (e.history[idx30] ?? e.latest),
          diff60m: e.latest - (e.history[idx60] ?? e.latest),
        };
      },
    );
    // Sort descending by strike (top = highest price)
    normalized.sort((a, b) => b.price - a.price);
    return normalized;
  }, [frames, selector]);

  // Build heatmap frames from the fog grid (one per RTH minute).
  const heatmapFrames = useMemo<HeatmapFrame[]>(
    () =>
      frames.map((f) => ({
        ts: Math.floor(new Date(f.ts).getTime() / 1000),
        forward: f.forward,
        minute_index: f.minute_index,
        price_grid: f.fog?.price_grid ?? [],
        gamma: f.fog?.gamma ?? [],
        delta: f.fog?.delta ?? [],
      })),
    [frames],
  );

  // Derive major long/short levels from strikes
  const majorLongPrice = useMemo(
    () =>
      strikes.reduce(
        (a, b) => (b.current > a.current ? b : a),
        { price: 0, current: -Infinity } as StrikeData,
      ).price,
    [strikes],
  );
  const majorShortPrice = useMemo(
    () =>
      strikes.reduce(
        (a, b) => (b.current < a.current ? b : a),
        { price: 0, current: Infinity } as StrikeData,
      ).price,
    [strikes],
  );

  // Close dropdown on outside click / Escape
  useEffect(() => {
    if (!open) return;
    const onClick = (e: MouseEvent) => {
      if (!dropdownRef.current?.contains(e.target as Node)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("mousedown", onClick);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onClick);
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);

  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-black text-bone-0">
      {/* Selector dropdown — top-left
          Active item ditampilkan sebagai badge kotak (ada outline + bg).
          Saat dibuka, opsi lain mengembang ke SAMPING (horizontal) sebagai
          badge serupa, bukan dropdown vertikal. */}
      <div ref={dropdownRef} className="fixed left-8 top-[4.5rem] z-40">
        <div className="flex items-center gap-1.5">
          {/* Active badge — selalu kelihatan, klik untuk toggle */}
          <button
            type="button"
            onClick={() => setOpen((o) => !o)}
            className="rounded-[3px] border border-bone-0/60 bg-bone-0/[0.04] px-2.5 py-1 font-mono text-[12px] tracking-[0.18em] text-bone-0 transition-colors duration-150 hover:border-brick-glow hover:text-brick-glow"
            aria-haspopup="listbox"
            aria-expanded={open}
          >
            {selector}
          </button>
          {/* Other options — muncul di sebelah kanan saat open */}
          {open && (
            <ul
              role="listbox"
              className="flex items-center gap-1.5 font-mono text-[12px] tracking-[0.18em]"
            >
              {SELECTORS.filter((s) => s !== selector).map((s) => (
                <li key={s}>
                  <button
                    type="button"
                    role="option"
                    aria-selected={false}
                    onClick={() => {
                      setSelector(s);
                      setOpen(false);
                    }}
                    className="rounded-[3px] border border-rule bg-bone-0/[0.02] px-2.5 py-1 text-bone-3 transition-colors duration-150 hover:border-brick-glow hover:text-brick-glow"
                  >
                    {s}
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>

      {/* Main grid: [price+GEX combined] | rule | chart | rule | gradient
          Price ladder & GEX profile share a 24-row equal-height grid sehingga
          satu strike price selalu sejajar dengan satu bar GEX-nya. */}
      <div className="flex h-screen w-full items-stretch gap-0 px-8 pt-24 pb-20">
        <StrikePanel
          strikes={strikes}
          forward={forward}
          majorLongPrice={majorLongPrice}
          majorShortPrice={majorShortPrice}
          metric={selector}
        />
        <div className="mx-3 w-px bg-rule" aria-hidden="true" />
        <div className="relative flex flex-1 flex-col">
          {/* Heatmap GEX/DEX = chart utama. Price line (forward) digambar
              built-in di dalam canvas heatmap → satu sumbu harga, sync 100%
              dengan ladder kiri. Stats overlay di pojok kiri-atas. */}
          <div className="absolute inset-0 z-0">
            <GexHeatmap
              frames={heatmapFrames}
              metric={selector === "DEX" ? "delta" : "gamma"}
            />
          </div>
          <StatsOverlay forward={forward} regime={regime} pcRatio={pcRatio} />
        </div>
        <div className="mx-3 w-px bg-rule" aria-hidden="true" />
        <GradientRail />
      </div>

      {/* Bottom-left flash glyph */}
      <button
        type="button"
        aria-label="Quick action"
        className="fixed bottom-7 left-8 z-40 text-bone-3 transition-colors duration-150 hover:text-brick-glow"
      >
        <FlashIcon />
      </button>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* StrikePanel — price ladder + GEX profile dalam satu CSS grid         */
/* ------------------------------------------------------------------ */
/*                                                                      */
/* Tiap strike menempati 1 row di grid dengan tinggi yang sama          */
/* (`auto-rows-fr`), sehingga price label di kiri SELALU sejajar         */
/* dengan bar GEX-nya di kanan — apapun tinggi container.               */
/*                                                                      */
/* Layout per row:                                                      */
/*   ┌──────────┬──────────────────────────────────────────┐            */
/*   │  price   │            GEX profile bar              │            */
/*   │  (16w)   │  (history hairline + current pill)      │            */
/*   └──────────┴──────────────────────────────────────────┘            */
/*                                                                      */
/* Bar height = h-full (otomatis ngisi tinggi row), pill height         */
/* = persentase dari row biar ada ruang antar baris tanpa pakai gap.    */

function StrikePanel({
  strikes,
  forward,
  majorLongPrice,
  majorShortPrice,
  metric,
}: {
  strikes: StrikeData[];
  forward: number;
  majorLongPrice: number;
  majorShortPrice: number;
  metric: Selector;
}) {
  const TICK = 5;
  return (
    <div
      className="relative grid w-96 content-start overflow-y-auto py-1 fog-scroll"
      style={{ gridTemplateColumns: "4rem 1fr", gridAutoRows: "1.35rem" }}
    >
      {/* Center zero-axis (di kolom GEX, bukan kolom price) — pakai
          inset-x untuk align ke kolom kanan. Calc: width-price = 4rem +
          padding-x grid (px-3 di GexCell), jadi akan ditempatkan di
          dalam <GexCell /> aja biar sederhana. Lihat di sana. */}
      {strikes.map((s, i) => {
        const isCurrent = Math.abs(s.price - forward) < TICK / 2;
        const isLong = s.price === majorLongPrice;
        const isShort = s.price === majorShortPrice;
        const priceCls = isCurrent
          ? "text-amber-current"
          : isLong
            ? "text-turquoise-deep"
            : isShort
              ? "text-crimson-deep"
              : "text-bone-3";
        return (
          <Fragment key={s.price}>
            {/* Price cell */}
            <div className="flex items-center justify-end pr-3">
              <span
                className={`font-mono text-[10.5px] leading-none tabular-nums ${priceCls}`}
              >
                {s.price.toLocaleString("en-US")}
              </span>
            </div>
            {/* GEX cell */}
            <GexCell strike={s} showAxisTop={i === 0} metric={metric} />
          </Fragment>
        );
      })}
    </div>
  );
}

// Format a USD-notional value into a compact billion/million string.
function fmtNotional(v: number): string {
  const abs = Math.abs(v);
  const sign = v < 0 ? "-" : "";
  if (abs >= 1e9) return `${sign}$${(abs / 1e9).toFixed(2)}B`;
  if (abs >= 1e6) return `${sign}$${(abs / 1e6).toFixed(1)}M`;
  if (abs >= 1e3) return `${sign}$${(abs / 1e3).toFixed(1)}K`;
  return `${sign}$${abs.toFixed(0)}`;
}

// Signed delta with explicit +/- prefix.
function fmtDelta(v: number): string {
  return (v >= 0 ? "+" : "") + fmtNotional(v).replace("-", "");
}

function GexCell({
  strike,
  showAxisTop,
  metric,
}: {
  strike: StrikeData;
  showAxisTop: boolean;
  metric: Selector;
}) {
  const { current, low, high } = strike;
  const [hover, setHover] = useState(false);
  const [pos, setPos] = useState<{ x: number; y: number }>({ x: 0, y: 0 });
  const pct = (v: number) => `${(v * 50).toFixed(2)}%`;
  const positive = current >= 0;
  const color = positive ? "bg-turquoise-deep" : "bg-crimson-deep";

  // Pill geometry — width relatif terhadap setengah container.
  const pillLeft = positive ? "50%" : `calc(50% + ${pct(current)})`;
  const pillWidth = `${(Math.abs(current) * 50).toFixed(2)}%`;

  // History range hairline (low↔high) — bisa cross zero.
  const rangeLeft = `calc(50% + ${pct(low)})`;
  const rangeWidth = `${((high - low) * 50).toFixed(2)}%`;

  // Percentile of current within its historical [low, high] range.
  const span = strike.absHigh - strike.absLow;
  const percentile =
    span > 0 ? ((strike.absCurrent - strike.absLow) / span) * 100 : 0;

  return (
    <div
      className="relative flex h-full items-center pr-3"
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      onMouseMove={(e) => setPos({ x: e.clientX, y: e.clientY })}
    >
      {/* Center zero-axis: hanya digambar sekali per cell (tetap kelihatan
          continuous karena cells stack vertikal tanpa gap). */}
      <div
        className={`pointer-events-none absolute left-1/2 w-px -translate-x-1/2 bg-rule ${
          showAxisTop ? "top-0" : "-top-[1px]"
        } bottom-0`}
        aria-hidden="true"
      />
      {/* History range hairline — penanda historical low↔high.
          Di-center vertikal (top-1/2) biar sejajar dengan bar di tengah row;
          menjulur ke kiri/kanan ke titik terendah & tertinggi sepanjang sesi.
          End-cap kecil (whisker) di tiap ujung biar kebaca sebagai range. */}
      <div
        className="absolute top-1/2 h-px -translate-y-1/2 bg-bone-3/60"
        style={{ left: rangeLeft, width: rangeWidth }}
      />
      <div
        className="absolute top-1/2 h-2 w-px -translate-y-1/2 bg-bone-3/60"
        style={{ left: `calc(50% + ${pct(low)})` }}
        aria-hidden="true"
      />
      <div
        className="absolute top-1/2 h-2 w-px -translate-y-1/2 bg-bone-3/60"
        style={{ left: `calc(50% + ${pct(high)})` }}
        aria-hidden="true"
      />
      {/* Current GEX bar — kotak tapi sudut sedikit tumpul (rounded-[2px]),
          bukan rounded-full lagi. Tinggi 70% biar tetap ada ruang antar baris. */}
      <div
        className={`absolute rounded-[2px] ${color} ${
          hover ? "ring-1 ring-bone-0/50" : ""
        }`}
        style={{
          left: pillLeft,
          width: pillWidth,
          height: "70%",
          top: "15%",
        }}
      />
      {/* Hover tooltip — fixed ke posisi cursor biar tidak kepotong
          overflow-y panel. Isi: value (billion), percentile, momentum. */}
      {hover && (
        <div
          className="pointer-events-none fixed z-[100] w-64 rounded-[5px] border border-rule bg-black/95 px-4 py-3 font-mono shadow-xl backdrop-blur-sm"
          style={{ left: pos.x + 18, top: pos.y - 10 }}
        >
          <div className="flex items-center justify-between text-[12px] tracking-[0.12em] text-bone-3">
            <span>{metric}</span>
            <span className="tabular-nums text-bone-0">
              {strike.price.toLocaleString("en-US")}
            </span>
          </div>
          <div
            className={`mt-1.5 text-[24px] font-semibold leading-none tabular-nums ${
              strike.absCurrent >= 0 ? "text-turquoise-deep" : "text-crimson-deep"
            }`}
          >
            {fmtNotional(strike.absCurrent)}
          </div>
          <div className="mt-2 text-[11px] tabular-nums text-bone-3">
            {percentile.toFixed(0)}th pct · range {fmtNotional(strike.absLow)} →{" "}
            {fmtNotional(strike.absHigh)}
          </div>
          <div className="mt-2.5 space-y-1 border-t border-rule pt-2 text-[12px] tabular-nums">
            <TooltipRow label="last 5m" v={strike.diff5m} />
            <TooltipRow label="last 30m" v={strike.diff30m} />
            <TooltipRow label="last 60m" v={strike.diff60m} />
          </div>
        </div>
      )}
    </div>
  );
}

function TooltipRow({ label, v }: { label: string; v: number }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-bone-3">{label}</span>
      <span className={v >= 0 ? "text-turquoise-deep" : "text-crimson-deep"}>
        {fmtDelta(v)}
      </span>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* StatsOverlay — pojok kiri-atas DI DALAM chart (absolute overlay)    */
/* ------------------------------------------------------------------ */

function StatsOverlay({
  forward,
  regime,
  pcRatio,
}: {
  forward: number;
  regime: string;
  pcRatio: string;
}) {
  const currentPrice = forward;
  // Price change vs RTH open — not yet wired to real open; left at 0 until the
  // OHLC field is populated (options-only data has no futures candle).
  const priceChange = 0;
  const priceChangePct = currentPrice !== 0 ? (priceChange / currentPrice) * 100 : 0;

  const regimeColor =
    regime === "Long Gamma"
      ? "text-turquoise-deep"
      : regime === "Short Gamma"
        ? "text-crimson-deep"
        : "text-bone-3";

  return (
    <div className="pointer-events-none absolute left-4 top-3 z-10 flex flex-col gap-2.5">
      {/* /ES Price */}
      <div>
        <p className="font-mono text-[9px] uppercase tracking-[0.3em] text-bone-3">
          /ES Price
        </p>
        <p className="mt-0.5 font-mono text-[28px] font-medium leading-none tabular-nums text-amber-current">
          {currentPrice.toLocaleString("en-US", { maximumFractionDigits: 2 })}
        </p>
        <p
          className={`mt-0.5 font-mono text-[10px] tabular-nums ${
            priceChange < 0 ? "text-crimson-deep" : "text-turquoise-deep"
          }`}
        >
          {priceChange > 0 ? "+" : ""}
          {priceChange.toFixed(1)} ({priceChangePct > 0 ? "+" : ""}
          {priceChangePct.toFixed(2)}%)
        </p>
      </div>
      {/* Gamma Regime */}
      <div>
        <p className="font-mono text-[9px] uppercase tracking-[0.3em] text-bone-3">
          Gamma Regime
        </p>
        <p
          className={`mt-0.5 font-mono text-[13px] font-medium tracking-wide ${regimeColor}`}
        >
          {regime}
        </p>
      </div>
      {/* P/C Ratio */}
      <div>
        <p className="font-mono text-[9px] uppercase tracking-[0.3em] text-bone-3">
          P/C Ratio
        </p>
        <p className="mt-0.5 font-mono text-[13px] font-medium tabular-nums text-bone-0">
          {pcRatio}
        </p>
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Gradient rail                                                       */
/* ------------------------------------------------------------------ */

function GradientRail() {
  return (
    // Gradient rail bersih — TANPA grid hairline overlay (sebelumnya ada 9
    // garis hitam tipis yang bikin background terkesan "ber-grid").
    <div className="relative flex h-full w-7 flex-col overflow-hidden rounded-[6px]">
      <div
        className="h-full w-full"
        style={{
          background:
            "linear-gradient(to bottom, #0FB5A8 0%, #000000 50%, #B5002E 100%)",
        }}
      />
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Icons                                                               */
/* ------------------------------------------------------------------ */

function FlashIcon() {
  return (
    <svg
      width="18"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
    </svg>
  );
}
