"use client";

import { useEffect, useMemo, useState } from "react";
import {
  StrikeGutter,
  MetricBarPanel,
  type SmilePoint,
} from "@/components/fog/panels";
import {
  buildStrikeModel,
  buildSmile,
  type StrikeDatum,
  type SviParams,
} from "@/components/fog/strikeMath";
import { LevelsChartPanel } from "@/components/fog/LevelsChartPanel";
import { buildLevelsChart, type LevelsChartModel } from "@/components/fog/levelsChart";

/**
 * Fog — 0DTE GEX/DEX three-panel strike terminal.
 *
 * Data source: fetches real snapshot JSON from /data/ES_<date>.json
 * (generated by gen_session_snapshots.py). Falls back to synthetic data
 * if fetch fails (dev convenience).
 *
 * Layout (design spec 2026-06-17): four strike-aligned columns sharing one
 * Y axis (strike price), all scrolling together in one `fog-scroll` container:
 *   - gutter — price ladder (amber = current, turquoise/crimson = major long/short)
 *   - LEFT   — GEX structure (≈22% width): bidirectional bars + session
 *              range hairline + optional EXPERIMENTAL IV-smile overlay
 *   - RIGHT  — price × time tape (≈78% width): white spot line + dotted
 *              key-level tracks (turquoise call wall / amber zero-gamma /
 *              crimson put wall) the engine emits per minute
 *
 * Key levels (walls / gamma-flip) live in the Flux lens, not here.
 * The TRACE-style WebGL heatmap is retired (GexHeatmap.tsx / glHeatmap.ts kept
 * in the repo, just no longer imported). Two toggles (top-right) control the
 * IV-smile overlay and the flow animation; flow auto-disables under
 * prefers-reduced-motion.
 */

// Snapshot JSON types (matches engine output)
interface SnapshotProfile {
  strike: number;
  net_gex: number;
  net_dex: number;
  interpolated: boolean;
}

interface SnapshotLevels {
  gamma_flip: number | null;
  call_walls: number[];
  put_walls: number[];
  largest_gex: number | null;
  largest_dex: number | null;
}

// EXPERIMENTAL reverse-engineered SpotGamma-style levels (OI-gamma basis).
interface SnapshotProprietary {
  oi_gamma_flip: number | null;
  abs_gamma_strike: number | null;
  hedge_wall: number | null;
}

// EXPERIMENTAL volatility surface (SVI). Populated most frames; may be null.
interface SnapshotSurface {
  atm_vol: number;
  expected_move: number;
  skew: number;
  svi_a: number;
  svi_b: number;
  svi_rho: number;
  svi_m: number;
  svi_sigma: number;
}

interface SnapshotRegime {
  net_gamma: number;
  sign: number;
  stability_pct: number;
}

interface SnapshotFlux {
  total: number;
  calls: number;
  puts: number;
  zerodte: number;
  retail: number;
}

interface SnapshotFog {
  price_grid: number[];
  gamma: number[];
  delta: number[];
}

interface Snapshot {
  forward: number;
  minute_index: number;
  ts: string;
  profile: SnapshotProfile[];
  levels: SnapshotLevels;
  regime: SnapshotRegime;
  flux: SnapshotFlux | null;
  fog: SnapshotFog;
  surface: SnapshotSurface | null;
  proprietary: SnapshotProprietary | null;
}

// Fallback synthetic strikes if snapshot fetch fails (dev convenience).
function genSyntheticStrikes(): StrikeDatum[] {
  const STRIKE_COUNT = 24;
  const BASE_PRICE = 5_840;
  const TICK = 5;
  return Array.from({ length: STRIKE_COUNT }, (_, i) => {
    const price = BASE_PRICE + (STRIKE_COUNT - 1 - i) * TICK;
    const seed = (n: number) => {
      const t = Math.sin(i * 91.345 + n * 17.13) * 43758.5453;
      return t - Math.floor(t);
    };
    const mk = (a: number, b: number, c: number, d: number, e: number) => {
      const cur = (seed(a) - 0.5) * 2 * (0.4 + seed(b) * 0.6);
      const rng = 0.25 + seed(c) * 0.55;
      const lo = Math.max(-1, cur - rng * (0.3 + seed(d) * 0.7));
      const hi = Math.min(1, cur + rng * (0.3 + seed(e) * 0.7));
      return {
        current: cur,
        low: lo,
        high: hi,
        absCurrent: cur * 1e9,
        absLow: lo * 1e9,
        absHigh: hi * 1e9,
        diff5m: 100e6,
        diff30m: -200e6,
        diff60m: 150e6,
        diff5mNorm: (seed(a + 6) - 0.5) * 2,
      };
    };
    return { price, gex: mk(1, 2, 3, 4, 5), dex: mk(8, 9, 10, 11, 12) };
  });
}

export default function FogPage() {
  // IV-smile overlay toggle (default ON).
  const [showSmile, setShowSmile] = useState(true);

  // Snapshot data state. All frames of the session — needed to compute
  // per-strike session min/max + the 5-min momentum the center panel rides on.
  const [frames, setFrames] = useState<Snapshot[]>([]);
  const [forward, setForward] = useState<number>(5872);
  const [regime, setRegime] = useState<string>("Neutral");
  const [pcRatio, setPcRatio] = useState<string>("1.00");
  // Latest non-null SVI surface (last frame may be null).
  const [surface, setSurface] = useState<SviParams | null>(null);

  // Fetch snapshot JSON on mount
  useEffect(() => {
    const date = "2026-06-09";
    const instrument = "ES";
    const url = `/data/${instrument}_${date}.json`;

    fetch(url)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data: Snapshot[]) => {
        if (!data || data.length === 0) {
          throw new Error("Empty snapshot array");
        }

        setFrames(data);

        // Latest frame = the actual current state of the session (last minute).
        const frame = data[data.length - 1];
        setForward(frame.forward);

        // Derive gamma regime from net_gamma
        const netGamma = frame.regime.net_gamma;
        const regimeStr =
          netGamma > 0 ? "Long Gamma" : netGamma < 0 ? "Short Gamma" : "Neutral";
        setRegime(regimeStr);

        // P/C ratio from flux (puts vs calls dealer delta-notional). Falls back
        // to 1.00 when flux is absent (contract-valid optional field).
        if (frame.flux && frame.flux.calls !== 0) {
          const ratio = Math.abs(frame.flux.puts / frame.flux.calls);
          setPcRatio(ratio.toFixed(2));
        } else {
          setPcRatio("1.00");
        }

        // SVI surface: use the most recent non-null (last frame is null in data).
        let svi: SnapshotSurface | null = frame.surface;
        if (!svi) {
          for (let i = data.length - 1; i >= 0; i--) {
            if (data[i].surface) {
              svi = data[i].surface;
              break;
            }
          }
        }
        setSurface(svi);
      })
      .catch((err) => {
        console.warn("Snapshot fetch failed, using synthetic fallback:", err);
        setFrames([]);
        setForward(5872);
        setRegime("Neutral");
        setPcRatio("1.00");
        setSurface(null);
      });
  }, []);

  // Build the full strike model (GEX + DEX + session min/max + momentum) in one
  // pass at the engine's native $5 strike spacing. Pure + deterministic (see
  // strikeMath.test.ts).
  const strikes = useMemo<StrikeDatum[]>(() => {
    if (frames.length === 0) return genSyntheticStrikes();
    return buildStrikeModel(frames).strikes;
  }, [frames]);

  // Price chart + selectable key levels + session metrics for the right panel.
  const levelsChart = useMemo<LevelsChartModel>(() => buildLevelsChart(frames), [frames]);

  // Self-normalized IV-smile curve (vol vs strike) from the SVI surface.
  const smile = useMemo<SmilePoint[] | null>(() => {
    if (!surface || strikes.length === 0) return null;
    return buildSmile(strikes, forward, surface);
  }, [surface, strikes, forward]);

  // Major long/short strike (strongest current GEX each side) → gutter color.
  const majorLongPrice = useMemo(
    () =>
      strikes.reduce(
        (a, b) => (b.gex.current > a.gex.current ? b : a),
        strikes[0],
      )?.price ?? 0,
    [strikes],
  );
  const majorShortPrice = useMemo(
    () =>
      strikes.reduce(
        (a, b) => (b.gex.current < a.gex.current ? b : a),
        strikes[0],
      )?.price ?? 0,
    [strikes],
  );

  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-black text-bone-0">
      {/* IV-smile toggle — top-right. */}
      <div className="fixed right-8 top-[4.5rem] z-40 flex items-center gap-1.5 font-mono text-[12px] tracking-[0.18em]">
        <Toggle label="IV SMILE" on={showSmile} onClick={() => setShowSmile((v) => !v)} />
      </div>

      {/* Session readout — top header strip (was an in-chart overlay). */}
      <StatsOverlay forward={forward} regime={regime} pcRatio={pcRatio} />

      {/* Two zones side by side. ONLY the left strike stack (gutter + GEX)
          scrolls; the price×time chart on the right is fixed full-height. */}
      <div className="relative flex h-screen w-full items-stretch px-8 pt-24 pb-20">
        <div className="flex basis-[26%] shrink-0 items-stretch overflow-y-auto overflow-x-hidden fog-scroll">
          <StrikeGutter
            strikes={strikes}
            forward={forward}
            majorLongPrice={majorLongPrice}
            majorShortPrice={majorShortPrice}
          />
          <PanelRule label="GEX" />
          <MetricBarPanel
            strikes={strikes}
            metric="gex"
            label="GEX"
            smile={smile}
            showSmile={showSmile}
          />
        </div>
        <PanelRule label="PRICE · LEVELS" />
        <LevelsChartPanel model={levelsChart} className="grow" />
      </div>

      {/* Bottom-left flash glyph */}
      <button
        type="button"
        aria-label="Quick action"
        className="fixed bottom-7 left-8 z-40 text-bone-3 transition-colors duration-150 hover:text-brick-glow"
      >
        <FlashIcon />
      </button>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Small page-local chrome                                             */
/* ------------------------------------------------------------------ */

// A hairline separator between panels, with a vertical micro-label.
function PanelRule({ label }: { label: string }) {
  return (
    <div className="relative mx-3 w-px shrink-0 bg-rule" aria-hidden="true">
      <span
        className="absolute -top-6 left-1/2 -translate-x-1/2 whitespace-nowrap font-mono text-[8px] uppercase tracking-[0.25em] text-bone-3/70"
      >
        {label}
      </span>
    </div>
  );
}

// A control toggle matching the old selector aesthetic (rule border, mono
// micro-type, hover → brick). `on` = active layer; disabled greys it out.
function Toggle({
  label,
  on,
  onClick,
  disabled,
}: {
  label: string;
  on: boolean;
  onClick: () => void;
  disabled?: boolean;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      aria-pressed={on}
      className={`rounded-[3px] border px-2.5 py-1 transition-colors duration-150 ${
        disabled
          ? "cursor-not-allowed border-rule text-bone-3/40"
          : on
            ? "border-bone-0/60 bg-bone-0/[0.04] text-bone-0 hover:border-brick-glow hover:text-brick-glow"
            : "border-rule bg-bone-0/[0.02] text-bone-3 hover:border-brick-glow hover:text-brick-glow"
      }`}
    >
      {label}
    </button>
  );
}


/* ------------------------------------------------------------------ */
/* StatsOverlay — top header strip (price · regime · P/C)              */
/* ------------------------------------------------------------------ */

function StatsOverlay({
  forward,
  regime,
  pcRatio,
}: {
  forward: number;
  regime: string;
  pcRatio: string;
}) {
  const currentPrice = forward;
  // Price change vs RTH open — not yet wired to real open; left at 0 until the
  // OHLC field is populated (options-only data has no futures candle).
  const priceChange = 0;
  const priceChangePct = currentPrice !== 0 ? (priceChange / currentPrice) * 100 : 0;

  const regimeColor =
    regime === "Long Gamma"
      ? "text-turquoise-deep"
      : regime === "Short Gamma"
        ? "text-crimson-deep"
        : "text-bone-3";

  return (
    <div className="pointer-events-none fixed left-1/2 top-5 z-30 flex -translate-x-1/2 items-end gap-8">
      {/* /ES Price */}
      <div>
        <p className="font-mono text-[9px] uppercase tracking-[0.3em] text-bone-3">
          /ES Price
        </p>
        <p className="mt-0.5 font-mono text-[28px] font-medium leading-none tabular-nums text-amber-current">
          {currentPrice.toLocaleString("en-US", { maximumFractionDigits: 2 })}
        </p>
        <p
          className={`mt-0.5 font-mono text-[10px] tabular-nums ${
            priceChange < 0 ? "text-crimson-deep" : "text-turquoise-deep"
          }`}
        >
          {priceChange > 0 ? "+" : ""}
          {priceChange.toFixed(1)} ({priceChangePct > 0 ? "+" : ""}
          {priceChangePct.toFixed(2)}%)
        </p>
      </div>
      {/* Gamma Regime */}
      <div>
        <p className="font-mono text-[9px] uppercase tracking-[0.3em] text-bone-3">
          Gamma Regime
        </p>
        <p
          className={`mt-0.5 font-mono text-[13px] font-medium tracking-wide ${regimeColor}`}
        >
          {regime}
        </p>
      </div>
      {/* P/C Ratio */}
      <div>
        <p className="font-mono text-[9px] uppercase tracking-[0.3em] text-bone-3">
          P/C Ratio
        </p>
        <p className="mt-0.5 font-mono text-[13px] font-medium tabular-nums text-bone-0">
          {pcRatio}
        </p>
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Icons                                                               */
/* ------------------------------------------------------------------ */

function FlashIcon() {
  return (
    <svg
      width="18"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
    </svg>
  );
}
